from __future__ import annotations

from datetime import date
from pathlib import Path

import typer
from rich.console import Console

from pipeline.paths import data_root


app = typer.Typer(add_completion=False, no_args_is_help=True)
console = Console()


def _report_path(year: int) -> Path:
    return data_root() / "reports" / f"{year}.mdx"


@app.command()
def main(year: int = typer.Option(..., "--year")) -> None:
    """
    Generate a versioned annual report MDX in data/reports/.
    """
    out = _report_path(year)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "\n".join(
            [
                "---",
                f"title: GENARCH Annual Report {year}",
                f"year: {year}",
                f"generated_on: {date.today().isoformat()}",
                "---",
                "",
                "# GENARCH Annual Report",
                "",
                "This report is generated by the GENARCH pipeline.",
                "",
                "## Summary",
                "",
                "- Seed report placeholder for v1.0 bootstrap.",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    console.print(f"[bold green]Wrote report[/bold green] {out}")


if __name__ == "__main__":
    app()

